### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getPaths' of undefined

### ISSUE THREAD

**Issue by sunkibaek** [sindresorhus/atom-ava#22]
Recently, when I try to run ava test inside atom, it gives following error:

```
Uncaught TypeError: Cannot read property 'getPaths' of undefined
/Users/sunkibaek/.atom/packages/ava/lib/index.js:73
Hide Stack Trace
TypeError: Cannot read property 'getPaths' of undefined
    at Object.runAll (/Users/sunkibaek/.atom/packages/ava/lib/index.js:73:31)
    at atom-workspace.<anonymous> (/Users/sunkibaek/.atom/packages/ava/lib/index.js:16:62)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at CommandPaletteView.module.exports.CommandPaletteView.confirmed (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/command-palette/lib/command-palette-view.js:183:32)
    at CommandPaletteView.module.exports.SelectListView.confirmSelection (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:338:21)
    at space-pen-div.atom.commands.add.core:confirm (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-space-pen-views/lib/select-list-view.js:109:19)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom Beta.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:580:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:388:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:98:36)
    at HTMLDocument.<anonymous> (/Applications/Atom Beta.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

It used to work fine so I have no idea what has caused this. Any ideas? Thanks!

Atom version is 1.10.0-beta0 although the error started to happen before 1.10.0.

**Comment by skellock** [comment]
Fixed it up by changing that line to read:

``` js
// ~/.atom/packages/ava/lib/index:73
const paths = (editor.project || atom.project).getPaths();
```

Apparently `editor.project` is not a thing?  I'm not sure.

Another (ir)relevant note.   [My repo](https://github.com/skellock/reactotron/tree/next) is setup in a monorepo style.  

`Run All Tests` would actually tell me AVA couldn't find tests.  Which was right, of course.

So...

Instead of opening the folder in atom, open each `packages/*` using `File -> Add Project Folder`.  `Run All Tests` can then detect the folder properly and run it for each of the tests in that "sub-project".

Sorry for the awkward phrasing, coffee is yet to kick in.
